# Tested with golangci-lint ver. 2.x
version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - asciicheck        # checks for non-ASCII identifiers
    - bidichk           # checks for dangerous unicode sequences (security)
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errname           # checks error naming conventions
    - exhaustive
    - gocheckcompilerdirectives  # validates go compiler directives
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - staticcheck
    - govet
    - ineffassign
    - makezero          # finds slice declarations with non-zero initial length
    - misspell
    - nakedret
    - prealloc
    - reassign          # checks package variable reassignment
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: "logging is allowed only by logutils.Log"
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - ifElseChain
        - whyNoLint
        - unnamedResult
      settings:
        hugeParam:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 512
    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    lll:
      line-length: 140
    misspell:
      locale: US
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -QF1001
        - -QF1003
        - -QF1008
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
        - github.com/onsi/gomega/gstruct

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor/
      - .github/
      - docs/
      - images/
    rules:
      - path: _test\.go
        linters:
          - mnd
          - gosec
          - dupl
          - lll
          - goconst

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/k8snetworkplumbingwg/sriov-cni
