#!/usr/bin/env bash
set -e

ORG_PATH="github.com/hustcat"
REPO_PATH="${ORG_PATH}/sriov-cni"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export CGO_ENABLED=0
export GO15VENDOREXPERIMENT=1
export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

echo "Building plugins"
go install -tags no_openssl "$@" ${REPO_PATH}/sriov
go install -tags no_openssl "$@" ${REPO_PATH}/fixipam
