FROM ppc64le/golang:alpine as builder

ADD . /usr/src/sriov-cni

ENV HTTP_PROXY $http_proxy
ENV HTTPS_PROXY $https_proxy

RUN apk add --update --virtual build-dependencies build-base linux-headers make && \
    cd /usr/src/sriov-cni && \
    make clean && \
    make build

FROM ppc64le/alpine
COPY --from=builder /usr/src/sriov-cni/build/sriov /usr/bin/
WORKDIR /

LABEL io.k8s.display-name="SR-IOV CNI PPC64LE"

ADD ./images/entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
